# Generated by Django 4.1.1 on 2022-10-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionitem_delete_listing_alter_bid_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='bids',
            field=models.ManyToManyField(to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.comment'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='category',
            field=models.CharField(choices=[('', ''), ('1', 'Furniture'), ('2', 'Automobiles'), ('3', 'Pets'), ('4', 'Sporting Goods'), ('6', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
