# Generated by Django 4.1.1 on 2022-10-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watch',
            new_name='watchitem',
        ),
    ]
