# Generated by Django 4.1.1 on 2022-10-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_watch_watchlist_watchitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchitem',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(to='auctions.auctionitem'),
        ),
    ]
