# Generated by Django 4.1.1 on 2022-10-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_watchlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='bids',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionitem'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='bids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
