# Generated by Django 4.1.1 on 2022-10-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_auctionitem_bids_alter_watchlist_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='watchlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.watchlist'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.URLField(null=True),
        ),
    ]
