# Generated by Django 4.1.1 on 2022-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionitem_watchlist_watchlist_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.auctionitem'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
