# Generated by Django 4.1.1 on 2022-10-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_auctionitem_watchlist_user_watchlist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
        
    ]
