# Generated by Django 4.1.1 on 2022-10-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_delete_watchlist_alter_auctionitem_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bids',
            field=models.IntegerField(default=0),
        ),
    ]
