# Generated by Django 4.1.1 on 2022-10-17 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bid_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bids',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist_counter',
            field=models.IntegerField(blank=True),
        ),
    ]
