# Generated by Django 4.1.1 on 2022-10-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_auctionitem_bids_remove_auctionitem_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
