# Generated by Django 4.1.1 on 2022-10-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_auctionitem_startingbid_remove_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='minimum',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
