# Generated by Django 4.1.1 on 2022-10-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_auctionitem_minimum_auctionitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
