# Generated by Django 4.1.1 on 2022-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='bidcount',
            field=models.IntegerField(default=0),
        ),
    ]
