# Generated by Django 4.1.1 on 2022-11-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_bid_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_bidding_on', to='auctions.auctionitem'),
        ),
    ]
