# Generated by Django 4.1.1 on 2022-11-03 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auctionitem_bid_alter_bid_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='bid',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
