# Generated by Django 4.1.1 on 2022-11-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_remove_auctionitem_bid_auctionitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_commenting_on', to='auctions.auctionitem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.CharField(max_length=1000),
        ),
    ]
