# Generated by Django 4.1.1 on 2022-11-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_remove_watchlist_auctions_watchlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
